# Generated by Django 5.1.4 on 2025-04-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_clienteteste_data_nasc_clienteteste_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientParagrafOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, verbose_name='uid user')),
                ('ProcessNumer', models.CharField(max_length=40, verbose_name='Numero do processo')),
                ('NumberStickCriminal', models.CharField(max_length=40, verbose_name=' Numero da vara criminal')),
                ('CityComarc', models.CharField(max_length=40, verbose_name='Numero da comarca')),
                ('TypeAction', models.CharField(choices=[('AC', 'Ação Penal'), ('IP', 'Inquerito Policial')], max_length=2, verbose_name='Tipo da acusação')),
                ('PartOuter', models.CharField(max_length=40, verbose_name='Parte da autora')),
                ('NameAcused', models.CharField(max_length=40, verbose_name='Nome do acusado')),
                ('Nacionalit', models.CharField(max_length=15, verbose_name='Nacionalidade')),
                ('CivilState', models.CharField(max_length=15, verbose_name='Estado Civíl')),
                ('Cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('Address', models.CharField(max_length=150, verbose_name='Endereço')),
                ('State', models.CharField(choices=[('S', 'Preso'), ('N', 'Não Preso')], max_length=1, verbose_name='O cliente está preso?')),
                ('AnoterDefender', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nome do advogado de ataque')),
            ],
        ),
    ]
