# Generated by Django 5.1.4 on 2025-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_clientparagrafone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefesaPreliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID do usuário')),
                ('artigo_crime', models.CharField(max_length=50, verbose_name='Artigo ou tipo de crime')),
                ('data_fato', models.DateField(verbose_name='Data do fato')),
                ('local_fato', models.CharField(max_length=150, verbose_name='Local do fato')),
                ('admite_crime', models.BooleanField(verbose_name='O acusado admite o crime?')),
                ('havia_testemunhas', models.BooleanField(verbose_name='Havia testemunhas no momento do fato?')),
                ('descricao_testemunhas', models.TextField(blank=True, null=True, verbose_name='Informações sobre as testemunhas')),
                ('provas_mencionadas', models.TextField(blank=True, null=True, verbose_name='Provas apresentadas ou mencionadas')),
                ('antecedentes', models.BooleanField(verbose_name='O acusado possui antecedentes criminais?')),
                ('esta_preso', models.BooleanField(verbose_name='O acusado está preso atualmente?')),
                ('local_prisao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local da prisão')),
                ('em_liberdade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação se estiver em liberdade')),
                ('alibi_ou_testemunha_defesa', models.TextField(blank=True, null=True, verbose_name='Álibi ou testemunha de defesa')),
                ('mencionar_defesa_futura', models.BooleanField(verbose_name='Deseja mencionar que a defesa será apresentada em momento oportuno?')),
                ('tonalidade', models.CharField(choices=[('F', 'Formal técnico e objetivo'), ('E', 'Enfático e contundente'), ('N', 'Neutro')], max_length=1, verbose_name='Tom da peça')),
            ],
        ),
        migrations.AlterField(
            model_name='clientparagrafone',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='uid user'),
        ),
    ]
