# Generated by Django 5.1.4 on 2025-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_defesapreliminar_alter_clientparagrafone_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentacaoJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID do usuário')),
                ('falha_cumprimento_legal', models.BooleanField(default=False, verbose_name='Houve falha no cumprimento das formalidades legais?')),
                ('falha_qual', models.TextField(blank=True, null=True, verbose_name='Se sim, qual falha foi cometida?')),
                ('tratamento_injusto', models.TextField(blank=True, null=True, verbose_name='Defesa considera que o acusado foi tratado de forma injusta ou irregular?')),
                ('irregularidade_prisao', models.TextField(blank=True, null=True, verbose_name='Houve irregularidade no momento da prisão ou apreensão?')),
                ('direito_ampla_defesa', models.BooleanField(default=False, verbose_name='Foi desrespeitado o direito à ampla defesa e contraditório?')),
                ('direito_ampla_defesa_como', models.TextField(blank=True, null=True, verbose_name='Se sim, como?')),
                ('defesa_ouvida', models.BooleanField(default=False, verbose_name='A defesa foi ouvida de forma adequada durante o processo?')),
                ('defesa_prejuizos', models.TextField(blank=True, null=True, verbose_name='Se não, quais prejuízos isso causou?')),
                ('prova_testemunhal_suficiente', models.BooleanField(default=False, verbose_name='A prova testemunhal é suficiente para comprovar a autoria do crime?')),
                ('testemunhas_falha', models.TextField(blank=True, null=True, verbose_name='Se não, qual a contradição ou falha nas testemunhas?')),
                ('laudo_pericial_comprova', models.BooleanField(default=False, verbose_name='O laudo pericial comprova o vínculo do acusado com o fato?')),
                ('laudo_falha_ou_omissao', models.TextField(blank=True, null=True, verbose_name='Se não, explique qual falha ou omissão o laudo apresenta.')),
                ('materialidade_nao_comprovada', models.BooleanField(default=False, verbose_name='A defesa acredita que a materialidade do crime não foi comprovada?')),
                ('materialidade_por_que', models.TextField(blank=True, null=True, verbose_name='Se sim, por quê?')),
                ('alibi_comprova_inocencia', models.BooleanField(default=False, verbose_name='O acusado possui álibi ou outra prova que comprova sua inocência?')),
                ('alibi_descricao', models.TextField(blank=True, null=True, verbose_name='Se sim, qual é?')),
                ('acusacao_baseada_em_suposicoes', models.BooleanField(default=False, verbose_name='A acusação se baseia em provas indiretas ou apenas suposições?')),
                ('acusacao_natureza_provas', models.TextField(blank=True, null=True, verbose_name='Se sim, qual é a natureza das provas?')),
                ('estado_necessidade', models.BooleanField(default=False, verbose_name='A defesa alega que o acusado agiu em estado de necessidade?')),
                ('estado_necessidade_justificativa', models.TextField(blank=True, null=True, verbose_name='Se sim, qual a situação que justifica o estado de necessidade?')),
                ('legitima_defesa', models.BooleanField(default=False, verbose_name='A defesa invoca legítima defesa?')),
                ('legitima_defesa_explicacao', models.TextField(blank=True, null=True, verbose_name='Se sim, explique como o acusado agiu em legítima defesa.')),
                ('erro_tipo_ou_proibicao', models.CharField(choices=[('erro_tipo', 'Erro de tipo'), ('erro_proibicao', 'Erro de proibição'), ('nao_aplica', 'Não se aplica')], default='nao_aplica', max_length=50, verbose_name='O acusado agiu em erro de tipo ou erro de proibição?')),
                ('erro_explicacao', models.TextField(blank=True, null=True, verbose_name='Se aplicável, como o erro ocorreu?')),
                ('coercao_moral_irresistivel', models.BooleanField(default=False, verbose_name='Houve alguma situação em que o acusado estava em uma situação de coação moral irresistível?')),
                ('coercao_moral_explicacao', models.TextField(blank=True, null=True, verbose_name='Se sim, explique.')),
                ('outras_causas_excluintes', models.BooleanField(default=False, verbose_name='Existem outras causas que excluem a ilicitude ou culpabilidade do acusado?')),
                ('outras_causas_excluintes_descr', models.TextField(blank=True, null=True, verbose_name='Se sim, quais são?')),
                ('presuncao_inocencia', models.BooleanField(default=False, verbose_name='O princípio da presunção de inocência foi violado?')),
                ('presuncao_inocencia_como', models.TextField(blank=True, null=True, verbose_name='Se sim, como?')),
                ('devido_processo_legal', models.BooleanField(default=False, verbose_name='O direito ao devido processo legal foi respeitado?')),
                ('devido_processo_legal_impactos', models.TextField(blank=True, null=True, verbose_name='Se não, quais etapas ou aspectos do processo foram afetados?')),
                ('proporcionalidade_violada', models.BooleanField(default=False, verbose_name='O princípio da proporcionalidade foi desrespeitado?')),
                ('proporcionalidade_como', models.TextField(blank=True, null=True, verbose_name='Se sim, explique como a medida aplicada foi desproporcional.')),
                ('cerceamento_defesa', models.BooleanField(default=False, verbose_name='Houve cerceamento de defesa?')),
                ('cerceamento_defesa_momento', models.TextField(blank=True, null=True, verbose_name='Se sim, em que momento o cerceamento ocorreu?')),
                ('dignidade_pessoa_humana', models.BooleanField(default=False, verbose_name='O princípio da dignidade da pessoa humana foi violado em algum momento do processo?')),
                ('dignidade_pessoa_humana_aspecto', models.TextField(blank=True, null=True, verbose_name='Se sim, em que aspecto?')),
                ('tratamento_diferenciado', models.BooleanField(default=False, verbose_name='O acusado foi tratado de forma diferenciada ou discriminatória durante o processo?')),
                ('tratamento_diferenciado_qual', models.TextField(blank=True, null=True, verbose_name='Se sim, qual o tratamento diferenciado?')),
                ('julgamento_imparcial', models.BooleanField(default=False, verbose_name='O acusado teve direito a um julgamento imparcial?')),
                ('julgamento_imparcial_como', models.TextField(blank=True, null=True, verbose_name='Se não, como isso ocorreu?')),
                ('circunstancia_relevante', models.BooleanField(default=False, verbose_name='Há alguma outra circunstância que a defesa considera relevante para a absolvição ou redução da pena?')),
                ('circunstancia_descricao', models.TextField(blank=True, null=True, verbose_name='Se sim, qual circunstância?')),
                ('pena_desproporcional', models.BooleanField(default=False, verbose_name='A defesa considera que a pena proposta é desproporcional em relação à gravidade do fato?')),
                ('pena_desproporcional_justificativa', models.TextField(blank=True, null=True, verbose_name='Se sim, explique por quê.')),
                ('jurisprudencia_favorece', models.BooleanField(default=False, verbose_name='Há alguma jurisprudência ou decisão anterior que favorece a defesa?')),
                ('jurisprudencia_descricao', models.TextField(blank=True, null=True, verbose_name='Se sim, qual jurisprudência?')),
            ],
        ),
    ]
