# Generated by Django 5.1.4 on 2025-04-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_argumentacaojuridica'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentoAbsolvicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDefesaPenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID do usuário')),
                ('pedido_principal', models.CharField(choices=[('extincao', 'Extinção da ação penal'), ('absolvicao_sumaria', 'Absolvição sumária'), ('trancamento', 'Trancamento da ação penal'), ('arquivamento', 'Arquivamento'), ('outro', 'Outro (especificar)')], max_length=30)),
                ('outro_pedido_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('incluir_absolvicao_como_alternativa', models.BooleanField()),
                ('outro_fundamento_absolvicao', models.CharField(blank=True, max_length=255, null=True)),
                ('esta_preso', models.BooleanField()),
                ('solicitar_alvara', models.BooleanField(default=False)),
                ('pedir_medidas_cautelares', models.BooleanField(default=False)),
                ('medidas_cautelares', models.TextField(blank=True, null=True)),
                ('incluir_pedido_subsidiario', models.BooleanField(default=False)),
                ('pedido_subsidiario', models.TextField(blank=True, null=True)),
                ('requerer_nao_recebimento_denuncia', models.BooleanField(default=False)),
                ('requerer_prioridade', models.BooleanField(default=False)),
                ('requerer_acesso_provas', models.BooleanField(default=False)),
                ('quais_provas', models.TextField(blank=True, null=True)),
                ('outros_pedidos', models.TextField(blank=True, null=True)),
                ('fundamentos_absolvicao', models.ManyToManyField(to='recipes.fundamentoabsolvicao')),
            ],
        ),
    ]
