# Generated by Django 5.1.4 on 2025-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_pedidodefesapenal_fundamentos_absolvicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentoabsolvicao',
            name='codigo',
            field=models.CharField(choices=[('inexistencia_fato', 'Inexistência do fato'), ('fato_atipico', 'Fato atípico'), ('excludente_ilicitude', 'Excludente de ilicitude'), ('excludente_culpabilidade', 'Excludente de culpabilidade'), ('ausencia_autoria', 'Ausência de indícios suficientes de autoria'), ('outro', 'Outro (especificar)')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='pedidodefesapenal',
            name='fundamentos_absolvicao',
        ),
        migrations.AddField(
            model_name='pedidodefesapenal',
            name='fundamentos_absolvicao',
            field=models.ManyToManyField(blank=True, to='recipes.fundamentoabsolvicao'),
        ),
    ]
