# Generated by Django 5.1.4 on 2025-04-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_pedidodefesapenal_fundamentos_absolvicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacaoEJurisprudencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='UID do usuário')),
                ('certidao', models.TextField(blank=True, help_text='Descreva a certidão relevante para o caso (ex.: certidão de antecedentes criminais).', null=True)),
                ('laudo', models.TextField(blank=True, help_text='Descreva o laudo técnico ou pericial relevante para o caso (ex.: exame toxicológico, laudo do IML).', null=True)),
                ('testemunha_nome', models.CharField(blank=True, help_text='Nome completo da testemunha, se houver.', max_length=255, null=True)),
                ('testemunha_qualificacao', models.TextField(blank=True, help_text='Qualificação da testemunha (ex.: profissão, relação com o réu).', null=True)),
                ('jurisprudencias', models.TextField(blank=True, help_text='Jurispurências específicas já separadas (ex.: número do processo ou ementa).', null=True)),
                ('incluir_jurisprudencia_apoio', models.BooleanField(default=False, help_text='Deseja incluir jurisprudências de apoio para a sua tese principal?')),
                ('tese_juridica_apoio', models.CharField(blank=True, help_text='Qual a tese jurídica que deseja reforçar com jurisprudência? (ex.: ausência de justa causa).', max_length=255, null=True)),
                ('julgado_especifico', models.TextField(blank=True, help_text='Cole o número do HC, REsp ou a ementa do julgado específico que gostaria de citar.', null=True)),
            ],
        ),
    ]
